### ISSUE TITLE
os.path.join shouldn't be used for concatenating bucket paths

### ISSUE THREAD

**Issue by DANIELF01** [yaojiach/red-panda#1]
I've be using the redshift_to_s3 method line 707 and it was failing due to the use of os.path.join. os.path.join will drop earlier arguments if a later argument appears as a absolute path i.e  as a S3_PATH would. 

![image](https://user-images.githubusercontent.com/11811970/43554575-a9d9e510-9638-11e8-8b96-658a52580c60.png)

I will work through a make a pull request.

**Comment by yaojiach** [comment]
Thanks for opening the issue. My intention was not to use 'absolute path' here. Mostly to be consistent with the rest of the API, as well as conventions used in `Boto3`. So users don't need to worry about the actual destination string and can simply provide a bucket name, a key (in our case: 'path' or 'path' + prefix).
